apply plugin: 'java'
apply plugin: 'maven-publish'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
version = '1.0'
group = 'com.github.Anuken'

sourceSets.main.java.srcDirs = [ "src/" ]
sourceSets.main.java.exclude("emu/**")

repositories {
    mavenLocal()
    mavenCentral()
    google()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    maven { url 'https://jitpack.io' }
}

ext {
    gdxVersion = '1.14.2'
    gdxControllersVersion = '1.9.13'
}

tasks.register('sourcesJar', Jar) {
    dependsOn classes
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-controllers:$gdxControllersVersion"
}
